# Generated by Django 5.1.7 on 2025-04-08 08:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('scraping', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(blank=True, max_length=50, null=True)),
                ('company', models.CharField(blank=True, max_length=255, null=True)),
                ('position', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(choices=[('not_contacted', 'Non contacté'), ('contacted', 'Contacté'), ('interested', 'Intéressé'), ('not_interested', 'Pas intéressé'), ('converted', 'Converti'), ('rejected', 'Rejeté')], default='not_contacted', max_length=20)),
                ('source', models.CharField(blank=True, max_length=100, null=True)),
                ('source_url', models.URLField(blank=True, max_length=500, null=True)),
                ('data', models.JSONField(blank=True, default=dict)),
                ('notes', models.TextField(blank=True)),
                ('priority', models.PositiveSmallIntegerField(default=0)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_contacted_at', models.DateTimeField(blank=True, null=True)),
                ('scraping_result', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to='scraping.scrapingresult')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leads', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Lead',
                'verbose_name_plural': 'Leads',
                'ordering': ['-created_at'],
            },
        ),
    ]
