# Generated by Django 5.1.7 on 2025-04-09 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_lead'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='accept_contact',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customuser',
            name='cgu_accepted',
            field=models.BooleanField(default=False),
        ),
    ]
