# Generated by Django 5.1.7 on 2025-04-17 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_lead_is_complete_lead_missing_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='incomplete_leads',
            field=models.IntegerField(default=0, help_text='Leads non créés car des champs obligatoires étaient manquants'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='rate_limited_leads',
            field=models.IntegerField(default=0, help_text="Leads non créés car l'utilisateur a atteint sa limite"),
        ),
    ]
