# Generated by Django 5.1.7 on 2025-04-17 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraping', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scrapingtask',
            name='incomplete_leads',
            field=models.IntegerField(default=0, help_text='Leads non créés car des champs obligatoires étaient manquants'),
        ),
        migrations.AddField(
            model_name='scrapingtask',
            name='rate_limited_leads',
            field=models.IntegerField(default=0, help_text="Leads non créés car l'utilisateur a atteint sa limite"),
        ),
    ]
